In [1]:
#import necessary modules
import pandas as pd

#read the csv file - heart dataset
heart_data=pd.read_csv('heart.csv')

#display the first five rows of the data
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [2]:
#display the first five rows of the data
heart_data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [3]:
#understanding the data type of each column of the dataset
heart_data.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [4]:
# select columns other than 'target' because it is the column we want to predict, so it should not be a part of the data
cols = [col for col in heart_data.columns if col not in ['target']]

# dropping the 'target' column from the dataset
data = heart_data[cols]

#assigning the 'target' column as our_target
our_target = heart_data['target']
data.head(n=2)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2

In [5]:
#DIVIDING TEST DATA AND TRAIN DATA

#importing train_test_split module
from sklearn.model_selection import train_test_split

#split data set into train and test sets using train_test_split() method
#test_size = 0.30 :30% of the data is take as test data and 70% as train data
#random_state ensures that we get a reproducible result every time
data_train, data_test, our_target_train, our_target_test = train_test_split(data,our_target, test_size = 0.30, random_state = 10)

In [7]:
# import the necessary module
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
#create an object of the type GaussianNB
gnb = GaussianNB()
#train the algorithm on training data and predict using the testing data
pred = gnb.fit(data_train, our_target_train).predict(data_test)
#print(pred.tolist())
#print the accuracy score of the model
print("Naive-Bayes accuracy : ",accuracy_score(our_target_test, pred, normalize = True))

Naive-Bayes accuracy :  0.7912087912087912

In [102]:
data_one=data.copy()
data_one

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2
10,54,1,0,140,239,0,1,160,0,1.2,2,0,2
11,48,0,2,130,275,0,1,139,0,0.2,2,0,2
12,49,1,1,130,266,0,1,171,0,0.6,2,0,2
13,64,1,3,110,211,0,0,144,1,1.8,1,0,2
14,58,0,3,150,283,1,0,162,0,1.0,2,0,2
15,50,0,2,120,219,0,1,158,0,1.6,1,0,2
16,58,0,2,120,340,0,1,172,0,0.0,2,0,2
17,66,0,3,150,226,0,1,114,0,2.6,0,0,2
18,43,1,0,150,247,0,1,171,0,1.5,2,0,2
19,69,0,3,140,239,0,1,151,0,1.8,2,2,2
20,59,1,0,135,234,0,1,161,0,0.5,1,0,3
21,44,1,2,130,233,0,1,179,1,0.4,2,0,2
22,42,1,0,140,226,0,1,178,0,0.0,2,0,2
23,61,1,2,150,243,1,1,137,1,1.0,1,0,2
24,40,1,3,140,199,0,1,178,1,1.4,2,0,3
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2
26,59,1,2,150,212,1,1,157,0,1.6,2,0,2
27,51,1,2,110,175,0,1,123,0,0.6,2,0,2
28,65,0,2,140,417,1,0,157,0,0.8,2,1,2
29,53,1,2,130,197,1,0,152,0,1.2,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,58,1,0,100,234,0,1,156,0,0.1,2,1,3
274,47,1,0,110,275,0,0,118,1,1.0,1,1,2
275,52,1,0,125,212,0,1,168,0,1.0,2,2,3
276,58,1,0,146,218,0,1,105,0,2.0,1,1,3
277,57,1,1,124,261,0,1,141,0,0.3,2,0,3
278,58,0,1,136,319,1,0,152,0,0.0,2,2,2
279,61,1,0,138,166,0,0,125,1,3.6,1,1,2
280,42,1,0,136,315,0,1,125,1,1.8,1,0,1
281,52,1,0,128,204,1,1,156,1,1.0,1,0,0
282,59,1,2,126,218,1,1,134,0,2.2,1,1,1
283,40,1,0,152,223,0,1,181,0,0.0,2,0,3
284,61,1,0,140,207,0,0,138,1,1.9,2,1,3
285,46,1,0,140,311,0,1,120,1,1.8,1,2,3
286,59,1,3,134,204,0,1,162,0,0.8,2,2,2
287,57,1,1,154,232,0,0,164,0,0.0,2,1,2
288,57,1,0,110,335,0,1,143,1,3.0,1,1,3
289,55,0,0,128,205,0,2,130,1,2.0,1,1,3
290,61,1,0,148,203,0,1,161,0,0.0,2,1,3
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1
292,58,0,0,170,225,1,0,146,1,2.8,1,2,1
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3
294,44,1,0,120,169,0,1,144,1,2.8,0,0,1
295,63,1,0,140,187,0,0,144,1,4.0,2,2,3
296,63,0,0,124,197,0,1,136,1,0.0,1,0,2
297,59,1,0,164,176,1,0,90,0,1.0,1,2,1
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [103]:
#Randomly replace 20% of the 'cp' column with NaN values
import random
import numpy as np
pd.set_option('mode.chained_assignment', None)
#def input_nan(x,pct):
#    n = int(len(x)*(pct - x.isna().mean()))
#    idxs = np.random.choice(len(x), max(n,0), replace=False, p=x.notna()/x.notna().sum())
#    x.iloc[idxs] = np.nan


#df[['y','x1']].apply(input_nan, pct=.15)
#data[['chol']].apply(input_nan,pct=.2)
int(len(data_one[['cp']])*(.2-data_one[['cp']].isna().mean()))
n=int(len(data_one[['cp']])*(.2-data_one[['cp']].isna().mean()))
n
idxs=np.random.choice(len(data_one[['cp']]),max(n,0),replace=False)
print (idxs)

#data[['chol']].iloc[idxs]=np.nan
#idxs[1]
#data.loc[i,['chol']]=np.nan
#data[['chol']].isna().sum()
for i in idxs:
    data_one.loc[i,['cp']]=np.nan

data_one.loc[:,['cp']]

[ 66 164  39  69 166 105 147 272 129 121 268 243 239  77 170 110  74   4
 289  72 278 233 302  31  17 263 235 161   0 100 103 294  97 236 227 211
 113  16 260  26 240 241 245 279  52  81 127 299 124 213  45 185 222 232
 139 258 297 122  40 298]

      cp
0    NaN
1    2.0
2    1.0
3    1.0
4    NaN
5    0.0
6    1.0
7    1.0
8    2.0
9    2.0
10   0.0
11   2.0
12   1.0
13   3.0
14   3.0
15   2.0
16   NaN
17   NaN
18   0.0
19   3.0
20   0.0
21   2.0
22   0.0
23   2.0
24   3.0
25   1.0
26   NaN
27   2.0
28   2.0
29   2.0
..   ...
273  0.0
274  0.0
275  0.0
276  0.0
277  1.0
278  NaN
279  NaN
280  0.0
281  0.0
282  2.0
283  0.0
284  0.0
285  0.0
286  3.0
287  1.0
288  0.0
289  NaN
290  0.0
291  0.0
292  0.0
293  2.0
294  NaN
295  0.0
296  0.0
297  NaN
298  NaN
299  NaN
300  0.0
301  0.0
302  NaN

[303 rows x 1 columns]

In [104]:
#data_one is the dataset without the target column and with 20% missing values in the 'cp' column
data_one

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,NaN,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2.0,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1.0,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1.0,120,236,0,1,178,0,0.8,2,0,2
4,57,0,NaN,120,354,0,1,163,1,0.6,2,0,2
5,57,1,0.0,140,192,0,1,148,0,0.4,1,0,1
6,56,0,1.0,140,294,0,0,153,0,1.3,1,0,2
7,44,1,1.0,120,263,0,1,173,0,0.0,2,0,3
8,52,1,2.0,172,199,1,1,162,0,0.5,2,0,3
9,57,1,2.0,150,168,0,1,174,0,1.6,2,0,2
10,54,1,0.0,140,239,0,1,160,0,1.2,2,0,2
11,48,0,2.0,130,275,0,1,139,0,0.2,2,0,2
12,49,1,1.0,130,266,0,1,171,0,0.6,2,0,2
13,64,1,3.0,110,211,0,0,144,1,1.8,1,0,2
14,58,0,3.0,150,283,1,0,162,0,1.0,2,0,2
15,50,0,2.0,120,219,0,1,158,0,1.6,1,0,2
16,58,0,NaN,120,340,0,1,172,0,0.0,2,0,2
17,66,0,NaN,150,226,0,1,114,0,2.6,0,0,2
18,43,1,0.0,150,247,0,1,171,0,1.5,2,0,2
19,69,0,3.0,140,239,0,1,151,0,1.8,2,2,2
20,59,1,0.0,135,234,0,1,161,0,0.5,1,0,3
21,44,1,2.0,130,233,0,1,179,1,0.4,2,0,2
22,42,1,0.0,140,226,0,1,178,0,0.0,2,0,2
23,61,1,2.0,150,243,1,1,137,1,1.0,1,0,2
24,40,1,3.0,140,199,0,1,178,1,1.4,2,0,3
25,71,0,1.0,160,302,0,1,162,0,0.4,2,2,2
26,59,1,NaN,150,212,1,1,157,0,1.6,2,0,2
27,51,1,2.0,110,175,0,1,123,0,0.6,2,0,2
28,65,0,2.0,140,417,1,0,157,0,0.8,2,1,2
29,53,1,2.0,130,197,1,0,152,0,1.2,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,58,1,0.0,100,234,0,1,156,0,0.1,2,1,3
274,47,1,0.0,110,275,0,0,118,1,1.0,1,1,2
275,52,1,0.0,125,212,0,1,168,0,1.0,2,2,3
276,58,1,0.0,146,218,0,1,105,0,2.0,1,1,3
277,57,1,1.0,124,261,0,1,141,0,0.3,2,0,3
278,58,0,NaN,136,319,1,0,152,0,0.0,2,2,2
279,61,1,NaN,138,166,0,0,125,1,3.6,1,1,2
280,42,1,0.0,136,315,0,1,125,1,1.8,1,0,1
281,52,1,0.0,128,204,1,1,156,1,1.0,1,0,0
282,59,1,2.0,126,218,1,1,134,0,2.2,1,1,1
283,40,1,0.0,152,223,0,1,181,0,0.0,2,0,3
284,61,1,0.0,140,207,0,0,138,1,1.9,2,1,3
285,46,1,0.0,140,311,0,1,120,1,1.8,1,2,3
286,59,1,3.0,134,204,0,1,162,0,0.8,2,2,2
287,57,1,1.0,154,232,0,0,164,0,0.0,2,1,2
288,57,1,0.0,110,335,0,1,143,1,3.0,1,1,3
289,55,0,NaN,128,205,0,2,130,1,2.0,1,1,3
290,61,1,0.0,148,203,0,1,161,0,0.0,2,1,3
291,58,1,0.0,114,318,0,2,140,0,4.4,0,3,1
292,58,0,0.0,170,225,1,0,146,1,2.8,1,2,1
293,67,1,2.0,152,212,0,0,150,0,0.8,1,0,3
294,44,1,NaN,120,169,0,1,144,1,2.8,0,0,1
295,63,1,0.0,140,187,0,0,144,1,4.0,2,2,3
296,63,0,0.0,124,197,0,1,136,1,0.0,1,0,2
297,59,1,NaN,164,176,1,0,90,0,1.0,1,2,1
298,57,0,NaN,140,241,0,1,123,1,0.2,1,0,3
299,45,1,NaN,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0.0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0.0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,NaN,130,236,0,0,174,0,0.0,1,1,2

In [105]:
#number of missing values present in the 'cp' column of our dataset(data_one) 
#20% of the total_number of rows = 60 
data_one.loc[:,['cp']].isna().sum()

cp    60
dtype: int64

In [111]:
#replace missing values with mode
data_one.cp.fillna(data_one.cp.mode()[0],inplace=True)
data_one

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,0.0,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2.0,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1.0,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1.0,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0.0,120,354,0,1,163,1,0.6,2,0,2
5,57,1,0.0,140,192,0,1,148,0,0.4,1,0,1
6,56,0,1.0,140,294,0,0,153,0,1.3,1,0,2
7,44,1,1.0,120,263,0,1,173,0,0.0,2,0,3
8,52,1,2.0,172,199,1,1,162,0,0.5,2,0,3
9,57,1,2.0,150,168,0,1,174,0,1.6,2,0,2
10,54,1,0.0,140,239,0,1,160,0,1.2,2,0,2
11,48,0,2.0,130,275,0,1,139,0,0.2,2,0,2
12,49,1,1.0,130,266,0,1,171,0,0.6,2,0,2
13,64,1,3.0,110,211,0,0,144,1,1.8,1,0,2
14,58,0,3.0,150,283,1,0,162,0,1.0,2,0,2
15,50,0,2.0,120,219,0,1,158,0,1.6,1,0,2
16,58,0,0.0,120,340,0,1,172,0,0.0,2,0,2
17,66,0,0.0,150,226,0,1,114,0,2.6,0,0,2
18,43,1,0.0,150,247,0,1,171,0,1.5,2,0,2
19,69,0,3.0,140,239,0,1,151,0,1.8,2,2,2
20,59,1,0.0,135,234,0,1,161,0,0.5,1,0,3
21,44,1,2.0,130,233,0,1,179,1,0.4,2,0,2
22,42,1,0.0,140,226,0,1,178,0,0.0,2,0,2
23,61,1,2.0,150,243,1,1,137,1,1.0,1,0,2
24,40,1,3.0,140,199,0,1,178,1,1.4,2,0,3
25,71,0,1.0,160,302,0,1,162,0,0.4,2,2,2
26,59,1,0.0,150,212,1,1,157,0,1.6,2,0,2
27,51,1,2.0,110,175,0,1,123,0,0.6,2,0,2
28,65,0,2.0,140,417,1,0,157,0,0.8,2,1,2
29,53,1,2.0,130,197,1,0,152,0,1.2,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,58,1,0.0,100,234,0,1,156,0,0.1,2,1,3
274,47,1,0.0,110,275,0,0,118,1,1.0,1,1,2
275,52,1,0.0,125,212,0,1,168,0,1.0,2,2,3
276,58,1,0.0,146,218,0,1,105,0,2.0,1,1,3
277,57,1,1.0,124,261,0,1,141,0,0.3,2,0,3
278,58,0,0.0,136,319,1,0,152,0,0.0,2,2,2
279,61,1,0.0,138,166,0,0,125,1,3.6,1,1,2
280,42,1,0.0,136,315,0,1,125,1,1.8,1,0,1
281,52,1,0.0,128,204,1,1,156,1,1.0,1,0,0
282,59,1,2.0,126,218,1,1,134,0,2.2,1,1,1
283,40,1,0.0,152,223,0,1,181,0,0.0,2,0,3
284,61,1,0.0,140,207,0,0,138,1,1.9,2,1,3
285,46,1,0.0,140,311,0,1,120,1,1.8,1,2,3
286,59,1,3.0,134,204,0,1,162,0,0.8,2,2,2
287,57,1,1.0,154,232,0,0,164,0,0.0,2,1,2
288,57,1,0.0,110,335,0,1,143,1,3.0,1,1,3
289,55,0,0.0,128,205,0,2,130,1,2.0,1,1,3
290,61,1,0.0,148,203,0,1,161,0,0.0,2,1,3
291,58,1,0.0,114,318,0,2,140,0,4.4,0,3,1
292,58,0,0.0,170,225,1,0,146,1,2.8,1,2,1
293,67,1,2.0,152,212,0,0,150,0,0.8,1,0,3
294,44,1,0.0,120,169,0,1,144,1,2.8,0,0,1
295,63,1,0.0,140,187,0,0,144,1,4.0,2,2,3
296,63,0,0.0,124,197,0,1,136,1,0.0,1,0,2
297,59,1,0.0,164,176,1,0,90,0,1.0,1,2,1
298,57,0,0.0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,0.0,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0.0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0.0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,0.0,130,236,0,0,174,0,0.0,1,1,2

In [112]:
data_one[['cp']].isna().sum()

cp    0
dtype: int64

In [113]:
#DIVIDING TEST DATA AND TRAIN DATA

#importing train_test_split module
from sklearn.model_selection import train_test_split

#split data set into train and test sets using train_test_split() method
#test_size = 0.30 :30% of the data is take as test data and 70% as train data
#random_state ensures that we get a reproducible result every time
data_train_one, data_test_one, our_target_train_one, our_target_test_one = train_test_split(data_one,our_target, test_size = 0.30, random_state = 10)

In [114]:
# import the necessary module
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

#create an object of the type GaussianNB
gnb = GaussianNB()

#train the algorithm on training data and predict using the testing data
#predict the test data (test_data_one) 
#using the train data (data_train_one) and train of target data(our_target_train_one)
pred = gnb.fit(data_train_one, our_target_train_one).predict(data_test_one)

#print the accuracy score of the model
print("Naive-Bayes accuracy : ",accuracy_score(our_target_test_one, pred, normalize = True))

Naive-Bayes accuracy :  0.7802197802197802

In [25]:
#Ignoring the data rows with missing values
# Will drop all rows that have any missing values.
#data_one.dropna(inplace=True)

In [24]:
#printing the dataset after dropping the rows containing null values
#data_one

In [23]:
#Reset the index values of the dataset or else cannot divide test and train data
#data_one.reset_index(drop=True)

In [13]:
#IMPUTATION USING MEAN VALUES

#Impute the values using scikit-learn SimpleImpute Class
from sklearn.impute import SimpleImputer

#strategy is taken as'mean' because imputation using mean value should be applied
imp_mean = SimpleImputer( strategy='mean') 

#'fit' fits the imputer on data
imp_mean.fit(data_one)

#'transform' imputes all missing values with mean values in data_one and copies to imputed_data_one
imputed_data_one = imp_mean.transform(data_one)

#imputed_data_one is converted into a DataFrame
imputed_data_one=pd.DataFrame(imputed_data_one)

#Printing imputed_data_one
imputed_data_one

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,63.0,1.0,3.000000,145.0,233.0,1.0,0.0,150.0,0.0,2.3,0.0,0.0,1.0
1,37.0,1.0,2.000000,130.0,250.0,0.0,1.0,187.0,0.0,3.5,0.0,0.0,2.0
2,41.0,0.0,1.000000,130.0,204.0,0.0,0.0,172.0,0.0,1.4,2.0,0.0,2.0
3,56.0,1.0,0.987654,120.0,236.0,0.0,1.0,178.0,0.0,0.8,2.0,0.0,2.0
4,57.0,0.0,0.000000,120.0,354.0,0.0,1.0,163.0,1.0,0.6,2.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57.0,0.0,0.000000,140.0,241.0,0.0,1.0,123.0,1.0,0.2,1.0,0.0,3.0
299,45.0,1.0,3.000000,110.0,264.0,0.0,1.0,132.0,0.0,1.2,1.0,0.0,3.0
300,68.0,1.0,0.987654,144.0,193.0,1.0,1.0,141.0,0.0,3.4,1.0,2.0,3.0
301,57.0,1.0,0.987654,130.0,131.0,0.0,1.0,115.0,1.0,1.2,1.0,1.0,3.0
302,57.0,0.0,0.987654,130.0,236.0,0.0,0.0,174.0,0.0,0.0,1.0,1.0,2.0

In [14]:
#DIVIDING TEST DATA AND TRAIN DATA

#importing train_test_split module
from sklearn.model_selection import train_test_split

#split data set into train and test sets using train_test_split() method
#test_size = 0.30 :30% of the data is take as test data and 70% as train data
#random_state ensures that we get a reproducible result every time
data_train_one, data_test_one, our_target_train_one, our_target_test_one = train_test_split(imputed_data_one,our_target, test_size = 0.30, random_state = 10)

In [15]:
# import the necessary module
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

#create an object of the type GaussianNB
gnb = GaussianNB()

#train the algorithm on training data and predict using the testing data
#predict the test data (test_data_one) 
#using the train data (data_train_one) and train of target data(our_target_train_one)
pred = gnb.fit(data_train_one, our_target_train_one).predict(data_test_one)

#print the accuracy score of the model
print("Naive-Bayes accuracy : ",accuracy_score(our_target_test_one, pred, normalize = True))

Naive-Bayes accuracy :  0.7802197802197802

In [16]:
#IMPUTATION USING MEDIAN VALUE

#Impute the values using scikit-learn SimpleImpute Class
from sklearn.impute import SimpleImputer

#strategy is taken as'median' because imputation using median value should be applied
imp_median = SimpleImputer( strategy='median') 

#'fit' fits the imputer on data
#data_one is our dataset without the target column
imp_median.fit(data_one)

#'transform' imputes all missing values with median values in data_one and copies to imputed_data_two
imputed_data_two = imp_median.transform(data_one)

#imputed_data_two is converted into a DataFrame
imputed_data_two=pd.DataFrame(imputed_data_two)

#printing imputed_data_two
imputed_data_two

        0    1    2      3      4    5    6      7    8    9   10   11   12
0    63.0  1.0  3.0  145.0  233.0  1.0  0.0  150.0  0.0  2.3  0.0  0.0  1.0
1    37.0  1.0  2.0  130.0  250.0  0.0  1.0  187.0  0.0  3.5  0.0  0.0  2.0
2    41.0  0.0  1.0  130.0  204.0  0.0  0.0  172.0  0.0  1.4  2.0  0.0  2.0
3    56.0  1.0  1.0  120.0  236.0  0.0  1.0  178.0  0.0  0.8  2.0  0.0  2.0
4    57.0  0.0  0.0  120.0  354.0  0.0  1.0  163.0  1.0  0.6  2.0  0.0  2.0
..    ...  ...  ...    ...    ...  ...  ...    ...  ...  ...  ...  ...  ...
298  57.0  0.0  0.0  140.0  241.0  0.0  1.0  123.0  1.0  0.2  1.0  0.0  3.0
299  45.0  1.0  3.0  110.0  264.0  0.0  1.0  132.0  0.0  1.2  1.0  0.0  3.0
300  68.0  1.0  1.0  144.0  193.0  1.0  1.0  141.0  0.0  3.4  1.0  2.0  3.0
301  57.0  1.0  1.0  130.0  131.0  0.0  1.0  115.0  1.0  1.2  1.0  1.0  3.0
302  57.0  0.0  1.0  130.0  236.0  0.0  0.0  174.0  0.0  0.0  1.0  1.0  2.0

[303 rows x 13 columns]

In [17]:
#DIVIDING TEST DATA AND TRAIN DATA

#importing train_test_split module
from sklearn.model_selection import train_test_split

#split data set into train and test sets using train_test_split() method
#test_size = 0.30 :30% of the data is take as test data and 70% as train data
#random_state ensures that we get a reproducible result every time
data_train_two, data_test_two, our_target_train_two, our_target_test_two = train_test_split(imputed_data_two,our_target, test_size = 0.30, random_state = 10)

In [18]:
# import the necessary module
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

#create an object of the type GaussianNB
gnb = GaussianNB()
#train the algorithm on training data and predict using the testing data
#predict the test data (test_data_two) 
#using the train data (data_train_two) and train of target data(our_target_train_two)
pred = gnb.fit(data_train_two, our_target_train_two).predict(data_test_two)

#print the accuracy score of the model
print("Naive-Bayes accuracy : ",accuracy_score(our_target_test_two, pred, normalize = True))

Naive-Bayes accuracy :  0.7802197802197802

In [35]:
#Impute the values using scikit-learn SimpleImpute Class
from sklearn.impute import SimpleImputer

#strategy is taken as'most_frequent' because imputation using most_frequent value should be applied
imp = SimpleImputer( strategy='most_frequent')

#'fit' fits the imputer on data
#data_one is our dataset without the target column
imp.fit(data_one)

#'transform' imputes all missing values with most_frequent values in data_one and copies to imputed_data_three
imputed_data_three = imp.transform(data_one)

#imputed_data_three is converted into a DataFrame
imputed_data_three=pd.DataFrame(imputed_data_three)

#Printing imputed_data_three
imputed_data_three

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,63.0,1.0,3.000000,145.0,233.0,1.0,0.0,150.0,0.0,2.3,0.0,0.0,1.0
1,37.0,1.0,2.000000,130.0,250.0,0.0,1.0,187.0,0.0,3.5,0.0,0.0,2.0
2,41.0,0.0,1.000000,130.0,204.0,0.0,0.0,172.0,0.0,1.4,2.0,0.0,2.0
3,56.0,1.0,1.520898,120.0,236.0,0.0,1.0,178.0,0.0,0.8,2.0,0.0,2.0
4,57.0,0.0,0.000000,120.0,354.0,0.0,1.0,163.0,1.0,0.6,2.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57.0,0.0,0.000000,140.0,241.0,0.0,1.0,123.0,1.0,0.2,1.0,0.0,3.0
299,45.0,1.0,3.000000,110.0,264.0,0.0,1.0,132.0,0.0,1.2,1.0,0.0,3.0
300,68.0,1.0,1.381096,144.0,193.0,1.0,1.0,141.0,0.0,3.4,1.0,2.0,3.0
301,57.0,1.0,0.200725,130.0,131.0,0.0,1.0,115.0,1.0,1.2,1.0,1.0,3.0
302,57.0,0.0,1.183591,130.0,236.0,0.0,0.0,174.0,0.0,0.0,1.0,1.0,2.0

In [20]:
#DIVIDING TEST DATA AND TRAIN DATA

#importing train_test_split module
from sklearn.model_selection import train_test_split

#split data set into train and test sets using train_test_split() method
#test_size = 0.30 :30% of the data is take as test data and 70% as train data
#random_state ensures that we get a reproducible result every time
data_train_three, data_test_three, our_target_train_three, our_target_test_three = train_test_split(imputed_data_three,our_target, test_size = 0.30, random_state = 10)

In [21]:
# import the necessary module
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

#create an object of the type GaussianNB
gnb = GaussianNB()

#train the algorithm on training data and predict using the testing data
#predict the test data (test_data_three) 
#using the train data (data_train_three) and train of target data(our_target_train_three)
pred = gnb.fit(data_train_three, our_target_train_three).predict(data_test_three)
#print(pred.tolist())
#print the accuracy score of the model
print("Naive-Bayes accuracy : ",accuracy_score(our_target_test_three, pred, normalize = True))

Naive-Bayes accuracy :  0.7692307692307693

In [22]:
import sys
from impyute.imputation.cs import fast_knn
sys.setrecursionlimit(100000) #Increase the recursion limit of the OS

# start the KNN training
imputed_data_four=fast_knn(data_one.values, k=30)

In [23]:
#DIVIDING TEST DATA AND TRAIN DATA

#importing train_test_split module
from sklearn.model_selection import train_test_split

#split data set into train and test sets using train_test_split() method
#test_size = 0.30 :30% of the data is take as test data and 70% as train data
#random_state ensures that we get a reproducible result every time
data_train_four, data_test_four, our_target_train_four, our_target_test_four = train_test_split(imputed_data_four,our_target, test_size = 0.30, random_state = 10)

In [24]:
# import the necessary module
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

#create an object of the type GaussianNB
gnb = GaussianNB()

#train the algorithm on training data and predict using the testing data
#predict the test data (test_data_four) 
#using the train data (data_train_four) and train of target data(our_target_train_four)
pred = gnb.fit(data_train_four, our_target_train_four).predict(data_test_four)

#print the accuracy score of the model
print("Naive-Bayes accuracy : ",accuracy_score(our_target_test_four, pred, normalize = True))

Naive-Bayes accuracy :  0.7802197802197802

In [25]:
from impyute.imputation.cs import mice

# start the MICE training
imputed_data_five=mice(data_one.values)

In [26]:
#DIVIDING TEST DATA AND TRAIN DATA

#importing train_test_split module
from sklearn.model_selection import train_test_split

#split data set into train and test sets using train_test_split() method
#test_size = 0.30 :30% of the data is take as test data and 70% as train data
#random_state ensures that we get a reproducible result every time
data_train_five, data_test_five, our_target_train_five, our_target_test_five = train_test_split(imputed_data_five,our_target, test_size = 0.30, random_state = 10)

In [27]:
# import the necessary module
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

#create an object of the type GaussianNB
gnb = GaussianNB()

#train the algorithm on training data and predict using the testing data
#predict the test data (test_data_five) 
#using the train data (data_train_five) and train of target data(our_target_train_five)
pred = gnb.fit(data_train_five, our_target_train_five).predict(data_test_five)

#print the accuracy score of the model
print("Naive-Bayes accuracy : ",accuracy_score(our_target_test_five, pred, normalize = True))

Naive-Bayes accuracy :  0.7802197802197802

In [28]:
import datawig


#divding the dataset into 
df_train, df_test = datawig.utils.random_split(data_one)



#Initialize a SimpleImputer model

imputer = datawig.SimpleImputer(

    input_columns=['age','sex','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal'], # column(s) containing information about the column we want to impute

    output_column= 'cp', # the column we'd like to impute values for

    output_path = 'imputer_model' # stores model data and metrics

    )



#Fit an imputer model on the train data

imputer.fit(train_df=df_train, num_epochs=50)



#Impute missing values and return original dataframe with predictions

imputed = imputer.predict(df_test)

2019-09-16 11:39:18,246 [INFO]
========== start: fit model
2019-09-16 11:39:18,249 [WARNING]  Already bound, ignoring bind()
2019-09-16 11:39:18,284 [INFO]  Epoch[0] Batch [0-7]	Speed: 7822.98 samples/sec	cross-entropy=16.856776	cp-accuracy=0.000000
2019-09-16 11:39:18,297 [INFO]  Epoch[0] Train-cross-entropy=11.707376
2019-09-16 11:39:18,298 [INFO]  Epoch[0] Train-cp-accuracy=0.000000
2019-09-16 11:39:18,302 [INFO]  Epoch[0] Time cost=0.045
2019-09-16 11:39:18,314 [INFO]  Saved checkpoint to "imputer_model/model-0000.params"
2019-09-16 11:39:18,327 [INFO]  Epoch[0] Validation-cross-entropy=8.298673
2019-09-16 11:39:18,328 [INFO]  Epoch[0] Validation-cp-accuracy=0.000000
2019-09-16 11:39:18,345 [INFO]  Epoch[1] Batch [0-7]	Speed: 9553.06 samples/sec	cross-entropy=13.174778	cp-accuracy=0.000000
2019-09-16 11:39:18,361 [INFO]  Epoch[1] Train-cross-entropy=9.293782
2019-09-16 11:39:18,363 [INFO]  Epoch[1] Train-cp-accuracy=0.000000
2019-09-16 11:39:18,390 [INFO]  Epoch[1] Time cost=0.060
2019-09-16 11:39:18,397 [INFO]  Saved checkpoint to "imputer_model/model-0001.params"
2019-09-16 11:39:18,403 [INFO]  Epoch[1] Validation-cross-entropy=7.430029
2019-09-16 11:39:18,404 [INFO]  Epoch[1] Validation-cp-accuracy=0.000000
2019-09-16 11:39:18,420 [INFO]  Epoch[2] Batch [0-7]	Speed: 9697.81 samples/sec	cross-entropy=12.129111	cp-accuracy=0.000000
2019-09-16 11:39:18,434 [INFO]  Epoch[2] Train-cross-entropy=8.282467
2019-09-16 11:39:18,436 [INFO]  Epoch[2] Train-cp-accuracy=0.000000
2019-09-16 11:39:18,437 [INFO]  Epoch[2] Time cost=0.032
2019-09-16 11:39:18,448 [INFO]  Saved checkpoint to "imputer_model/model-0002.params"
2019-09-16 11:39:18,453 [INFO]  Epoch[2] Validation-cross-entropy=7.321400
2019-09-16 11:39:18,454 [INFO]  Epoch[2] Validation-cp-accuracy=0.000000
2019-09-16 11:39:18,471 [INFO]  Epoch[3] Batch [0-7]	Speed: 9022.09 samples/sec	cross-entropy=11.380630	cp-accuracy=0.000000
2019-09-16 11:39:18,482 [INFO]  Epoch[3] Train-cross-entropy=7.649547
2019-09-16 11:39:18,483 [INFO]  Epoch[3] Train-cp-accuracy=0.000000
2019-09-16 11:39:18,486 [INFO]  Epoch[3] Time cost=0.030
2019-09-16 11:39:18,493 [INFO]  Saved checkpoint to "imputer_model/model-0003.params"
2019-09-16 11:39:18,497 [INFO]  Epoch[3] Validation-cross-entropy=7.540216
2019-09-16 11:39:18,499 [INFO]  Epoch[3] Validation-cp-accuracy=0.000000
2019-09-16 11:39:18,516 [INFO]  Epoch[4] Batch [0-7]	Speed: 9462.61 samples/sec	cross-entropy=10.729313	cp-accuracy=0.000000
2019-09-16 11:39:18,528 [INFO]  Epoch[4] Train-cross-entropy=7.189360
2019-09-16 11:39:18,530 [INFO]  Epoch[4] Train-cp-accuracy=0.000000
2019-09-16 11:39:18,532 [INFO]  Epoch[4] Time cost=0.030
2019-09-16 11:39:18,539 [INFO]  Saved checkpoint to "imputer_model/model-0004.params"
2019-09-16 11:39:18,543 [INFO]  Epoch[4] Validation-cross-entropy=7.836485
2019-09-16 11:39:18,546 [INFO]  Epoch[4] Validation-cp-accuracy=0.000000
2019-09-16 11:39:18,562 [INFO]  Epoch[5] Batch [0-7]	Speed: 9571.74 samples/sec	cross-entropy=10.169610	cp-accuracy=0.000000
2019-09-16 11:39:18,573 [INFO]  Epoch[5] Train-cross-entropy=6.813510
2019-09-16 11:39:18,575 [INFO]  Epoch[5] Train-cp-accuracy=0.000000
2019-09-16 11:39:18,577 [INFO]  Epoch[5] Time cost=0.030
2019-09-16 11:39:18,583 [INFO]  Saved checkpoint to "imputer_model/model-0005.params"
2019-09-16 11:39:18,589 [INFO]  Epoch[5] Validation-cross-entropy=8.081844
2019-09-16 11:39:18,589 [INFO]  Epoch[5] Validation-cp-accuracy=0.000000
2019-09-16 11:39:18,608 [INFO]  Epoch[6] Batch [0-7]	Speed: 9244.74 samples/sec	cross-entropy=9.681021	cp-accuracy=0.000000
2019-09-16 11:39:18,620 [INFO]  Epoch[6] Train-cross-entropy=6.497006
2019-09-16 11:39:18,621 [INFO]  Epoch[6] Train-cp-accuracy=0.000000
2019-09-16 11:39:18,623 [INFO]  Epoch[6] Time cost=0.031
2019-09-16 11:39:18,631 [INFO]  Saved checkpoint to "imputer_model/model-0006.params"
2019-09-16 11:39:18,639 [INFO]  No improvement detected for 5 epochs compared to 7.430028855800629 last error obtained: 8.324061930179596, stopping here
2019-09-16 11:39:18,641 [INFO]
========== done (0.3952667713165283 s) fit model
/anaconda3/lib/python3.6/site-packages/datawig/calibration.py:92: RuntimeWarning: invalid value encountered in log
  return np.log(probas)
/anaconda3/lib/python3.6/site-packages/datawig/calibration.py:59: RuntimeWarning: invalid value encountered in greater_equal
  bin_mask = (top_probas >= bin_lower) & (top_probas < bin_upper)
/anaconda3/lib/python3.6/site-packages/datawig/calibration.py:59: RuntimeWarning: invalid value encountered in less
  bin_mask = (top_probas >= bin_lower) & (top_probas < bin_upper)
/anaconda3/lib/python3.6/site-packages/datawig/imputer.py:822: FutureWarning: The 'contains' method is deprecated and will be removed in a future version. Use 'key in index' instead of 'index.contains(key)'
  if data_frame.columns.contains(imputation_col):

In [29]:
imputed

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,cp_imputed
85,67,0,2.0,115,564,0,0,160,0,1.6,1,0,3,0.711726
134,41,0,NaN,126,306,0,1,163,0,0.0,2,0,2,1.358574
143,67,0,0.0,106,223,0,1,142,0,0.3,2,2,2,1.086702
253,67,1,0.0,100,299,0,0,125,1,0.9,1,2,2,-0.269095
205,52,1,0.0,128,255,0,1,161,1,0.0,2,1,3,0.439954
266,55,0,0.0,180,327,0,2,117,1,3.4,1,0,2,1.118562
104,50,1,2.0,129,196,0,1,163,0,0.0,2,0,2,0.962082
34,51,1,3.0,125,213,0,0,125,1,1.4,2,1,2,0.516417
182,61,0,0.0,130,330,0,0,169,0,0.0,2,0,2,0.792950
108,50,0,1.0,120,244,0,1,162,0,1.1,2,0,2,1.414520
50,51,0,2.0,130,256,0,0,149,0,0.5,2,0,2,0.963724
254,59,1,3.0,160,273,0,0,125,0,0.0,2,0,2,1.512078
88,54,0,2.0,110,214,0,1,158,0,1.6,1,0,2,1.215480
263,63,0,0.0,108,269,0,1,169,1,1.8,1,2,2,0.072240
4,57,0,0.0,120,354,0,1,163,1,0.6,2,0,2,0.440157
133,41,1,1.0,110,235,0,1,153,0,0.0,2,0,2,1.252271
44,39,1,2.0,140,321,0,0,182,0,0.0,2,0,2,1.272318
250,51,1,0.0,140,298,0,1,122,1,4.2,1,3,3,0.136721
203,68,1,2.0,180,274,1,0,150,1,1.6,1,0,3,1.326614
135,49,0,NaN,130,269,0,1,163,0,0.0,2,0,2,1.220384
145,70,1,1.0,156,245,0,0,143,0,0.0,2,0,2,1.226240
71,51,1,NaN,94,227,0,1,154,1,0.0,2,1,3,0.624007
118,46,0,1.0,105,204,0,1,172,0,0.0,2,0,2,1.291020
274,47,1,0.0,110,275,0,0,118,1,1.0,1,1,2,0.083614
300,68,1,NaN,144,193,1,1,141,0,3.4,1,2,3,0.845943
216,62,0,2.0,130,263,0,1,97,0,1.2,1,1,3,1.018160
74,43,0,NaN,122,213,0,1,165,0,0.2,1,0,2,1.306679
298,57,0,0.0,140,241,0,1,123,1,0.2,1,0,3,0.568883
248,54,1,1.0,192,283,0,0,195,0,0.0,2,1,3,1.677472
94,45,0,1.0,112,160,0,1,138,0,0.0,1,0,2,1.297329
282,59,1,2.0,126,218,1,1,134,0,2.2,1,1,1,0.980812
93,54,0,NaN,132,288,1,0,159,1,0.0,2,1,2,0.498288
18,43,1,NaN,150,247,0,1,171,0,1.5,2,0,2,1.825987
31,65,1,0.0,120,177,0,1,140,0,0.4,2,0,3,0.767512
140,51,0,2.0,120,295,0,0,157,0,0.6,2,0,2,0.760300
89,58,0,0.0,100,248,0,0,122,0,1.0,1,0,2,0.586880
158,58,1,NaN,125,220,0,1,144,0,0.4,1,4,3,0.868007
141,43,1,0.0,115,303,0,1,181,0,1.2,1,0,2,1.555751
243,57,1,NaN,152,274,0,1,88,1,1.2,1,1,3,0.421142
13,64,1,3.0,110,211,0,0,144,1,1.8,1,0,2,0.126675
77,59,1,1.0,140,221,0,1,164,1,0.0,2,0,2,0.376088
290,61,1,0.0,148,203,0,1,161,0,0.0,2,1,3,0.783121
179,57,1,0.0,150,276,0,0,112,1,0.6,1,1,1,0.233471
177,64,1,2.0,140,335,0,1,158,0,0.0,2,0,2,1.222287
200,44,1,NaN,110,197,0,0,177,0,0.0,2,1,2,1.108144
33,54,1,2.0,125,273,0,0,152,0,0.5,0,1,2,1.125632
62,52,1,NaN,118,186,0,0,190,0,0.0,1,0,1,1.350796
122,41,0,2.0,112,268,0,0,172,1,0.0,2,0,2,0.195957
54,63,0,2.0,135,252,0,0,172,0,0.0,2,0,2,0.887530
239,35,1,0.0,126,282,0,0,156,1,0.0,2,0,3,0.541752
16,58,0,2.0,120,340,0,1,172,0,0.0,2,0,2,0.994392
40,51,0,2.0,140,308,0,0,142,0,1.5,2,1,2,0.798942
256,58,1,0.0,128,259,0,0,130,1,3.0,1,2,3,-0.009481
73,51,1,0.0,140,261,0,0,186,1,0.0,2,0,2,0.494299
8,52,1,2.0,172,199,1,1,162,0,0.5,2,0,3,1.532156
221,55,1,0.0,140,217,0,1,111,1,5.6,0,0,3,0.720750
156,47,1,2.0,130,253,0,1,179,0,0.0,2,0,2,1.010425
123,54,0,2.0,108,267,0,0,167,0,0.0,2,0,2,0.524581
15,50,0,2.0,120,219,0,1,158,0,1.6,1,0,2,1.371255
125,34,0,1.0,118,210,0,1,192,0,0.7,2,0,2,1.777938

In [30]:
imputedsort=imputed.sort_index()
imputedsort

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,cp_imputed
4,57,0,0.0,120,354,0,1,163,1,0.6,2,0,2,0.440157
8,52,1,2.0,172,199,1,1,162,0,0.5,2,0,3,1.532156
13,64,1,3.0,110,211,0,0,144,1,1.8,1,0,2,0.126675
15,50,0,2.0,120,219,0,1,158,0,1.6,1,0,2,1.371255
16,58,0,2.0,120,340,0,1,172,0,0.0,2,0,2,0.994392
18,43,1,NaN,150,247,0,1,171,0,1.5,2,0,2,1.825987
31,65,1,0.0,120,177,0,1,140,0,0.4,2,0,3,0.767512
33,54,1,2.0,125,273,0,0,152,0,0.5,0,1,2,1.125632
34,51,1,3.0,125,213,0,0,125,1,1.4,2,1,2,0.516417
40,51,0,2.0,140,308,0,0,142,0,1.5,2,1,2,0.798942
44,39,1,2.0,140,321,0,0,182,0,0.0,2,0,2,1.272318
50,51,0,2.0,130,256,0,0,149,0,0.5,2,0,2,0.963724
54,63,0,2.0,135,252,0,0,172,0,0.0,2,0,2,0.887530
62,52,1,NaN,118,186,0,0,190,0,0.0,1,0,1,1.350796
71,51,1,NaN,94,227,0,1,154,1,0.0,2,1,3,0.624007
73,51,1,0.0,140,261,0,0,186,1,0.0,2,0,2,0.494299
74,43,0,NaN,122,213,0,1,165,0,0.2,1,0,2,1.306679
77,59,1,1.0,140,221,0,1,164,1,0.0,2,0,2,0.376088
85,67,0,2.0,115,564,0,0,160,0,1.6,1,0,3,0.711726
88,54,0,2.0,110,214,0,1,158,0,1.6,1,0,2,1.215480
89,58,0,0.0,100,248,0,0,122,0,1.0,1,0,2,0.586880
93,54,0,NaN,132,288,1,0,159,1,0.0,2,1,2,0.498288
94,45,0,1.0,112,160,0,1,138,0,0.0,1,0,2,1.297329
104,50,1,2.0,129,196,0,1,163,0,0.0,2,0,2,0.962082
108,50,0,1.0,120,244,0,1,162,0,1.1,2,0,2,1.414520
118,46,0,1.0,105,204,0,1,172,0,0.0,2,0,2,1.291020
122,41,0,2.0,112,268,0,0,172,1,0.0,2,0,2,0.195957
123,54,0,2.0,108,267,0,0,167,0,0.0,2,0,2,0.524581
125,34,0,1.0,118,210,0,1,192,0,0.7,2,0,2,1.777938
133,41,1,1.0,110,235,0,1,153,0,0.0,2,0,2,1.252271
134,41,0,NaN,126,306,0,1,163,0,0.0,2,0,2,1.358574
135,49,0,NaN,130,269,0,1,163,0,0.0,2,0,2,1.220384
140,51,0,2.0,120,295,0,0,157,0,0.6,2,0,2,0.760300
141,43,1,0.0,115,303,0,1,181,0,1.2,1,0,2,1.555751
143,67,0,0.0,106,223,0,1,142,0,0.3,2,2,2,1.086702
145,70,1,1.0,156,245,0,0,143,0,0.0,2,0,2,1.226240
156,47,1,2.0,130,253,0,1,179,0,0.0,2,0,2,1.010425
158,58,1,NaN,125,220,0,1,144,0,0.4,1,4,3,0.868007
177,64,1,2.0,140,335,0,1,158,0,0.0,2,0,2,1.222287
179,57,1,0.0,150,276,0,0,112,1,0.6,1,1,1,0.233471
182,61,0,0.0,130,330,0,0,169,0,0.0,2,0,2,0.792950
200,44,1,NaN,110,197,0,0,177,0,0.0,2,1,2,1.108144
203,68,1,2.0,180,274,1,0,150,1,1.6,1,0,3,1.326614
205,52,1,0.0,128,255,0,1,161,1,0.0,2,1,3,0.439954
216,62,0,2.0,130,263,0,1,97,0,1.2,1,1,3,1.018160
221,55,1,0.0,140,217,0,1,111,1,5.6,0,0,3,0.720750
239,35,1,0.0,126,282,0,0,156,1,0.0,2,0,3,0.541752
243,57,1,NaN,152,274,0,1,88,1,1.2,1,1,3,0.421142
248,54,1,1.0,192,283,0,0,195,0,0.0,2,1,3,1.677472
250,51,1,0.0,140,298,0,1,122,1,4.2,1,3,3,0.136721
253,67,1,0.0,100,299,0,0,125,1,0.9,1,2,2,-0.269095
254,59,1,3.0,160,273,0,0,125,0,0.0,2,0,2,1.512078
256,58,1,0.0,128,259,0,0,130,1,3.0,1,2,3,-0.009481
263,63,0,0.0,108,269,0,1,169,1,1.8,1,2,2,0.072240
266,55,0,0.0,180,327,0,2,117,1,3.4,1,0,2,1.118562
274,47,1,0.0,110,275,0,0,118,1,1.0,1,1,2,0.083614
282,59,1,2.0,126,218,1,1,134,0,2.2,1,1,1,0.980812
290,61,1,0.0,148,203,0,1,161,0,0.0,2,1,3,0.783121
298,57,0,0.0,140,241,0,1,123,1,0.2,1,0,3,0.568883
300,68,1,NaN,144,193,1,1,141,0,3.4,1,2,3,0.845943

In [31]:
data_one[['cp']]
#imputed.loc[:,'cp_imputed']

      cp
0    3.0
1    2.0
2    1.0
3    NaN
4    0.0
..   ...
298  0.0
299  3.0
300  NaN
301  NaN
302  NaN

[303 rows x 1 columns]

# LINEAR REGRESSION

In [32]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
data_LR = data_one[['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']]

#Step-1: Spliting the dataset that contains the missing values and no missing values into test and train dataframe respectively.
x_train = data_LR[data_LR['cp'].notnull()].drop(columns='cp')
y_train = data_LR[data_LR['cp'].notnull()]['cp']
x_test = data_LR[data_LR['cp'].isnull()].drop(columns='cp')
y_test = data_LR[data_LR['cp'].isnull()]['cp']

#Step-2: Training the algorithm
linreg.fit(x_train, y_train)

#Step-3: Predict the missing values in the attribute of the test data.
predicted = linreg.predict(x_test)

#Step-4: Let’s obtain the complete dataset by combining with the target attribute.
data_one.cp[data_one.cp.isnull()] = predicted
data_one

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3.000000,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2.000000,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1.000000,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1.520898,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0.000000,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0.000000,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3.000000,110,264,0,1,132,0,1.2,1,0,3
300,68,1,1.381096,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0.200725,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1.183591,130,236,0,0,174,0,0.0,1,1,2

# KNN

In [33]:
from fancyimpute import KNN 
#We use the data_one dataframe from heart dataset

#fancy impute removes column names.
train_cols = list(data_one)

# Use 5 nearest rows which have a feature to fill in each row's missing features
data_one = pd.DataFrame(KNN(k=5).fit_transform(data_one))
data_one.columns = train_cols
data_one

Using TensorFlow backend.

Imputing row 1/303 with 0 missing, elapsed time: 0.034
Imputing row 101/303 with 0 missing, elapsed time: 0.035
Imputing row 201/303 with 0 missing, elapsed time: 0.035
Imputing row 301/303 with 0 missing, elapsed time: 0.036

/anaconda3/lib/python3.6/site-packages/fancyimpute/solver.py:55: UserWarning: Input matrix is not missing any values
  warnings.warn("Input matrix is not missing any values")

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63.0,1.0,3.000000,145.0,233.0,1.0,0.0,150.0,0.0,2.3,0.0,0.0,1.0
1,37.0,1.0,2.000000,130.0,250.0,0.0,1.0,187.0,0.0,3.5,0.0,0.0,2.0
2,41.0,0.0,1.000000,130.0,204.0,0.0,0.0,172.0,0.0,1.4,2.0,0.0,2.0
3,56.0,1.0,1.520898,120.0,236.0,0.0,1.0,178.0,0.0,0.8,2.0,0.0,2.0
4,57.0,0.0,0.000000,120.0,354.0,0.0,1.0,163.0,1.0,0.6,2.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57.0,0.0,0.000000,140.0,241.0,0.0,1.0,123.0,1.0,0.2,1.0,0.0,3.0
299,45.0,1.0,3.000000,110.0,264.0,0.0,1.0,132.0,0.0,1.2,1.0,0.0,3.0
300,68.0,1.0,1.381096,144.0,193.0,1.0,1.0,141.0,0.0,3.4,1.0,2.0,3.0
301,57.0,1.0,0.200725,130.0,131.0,0.0,1.0,115.0,1.0,1.2,1.0,1.0,3.0
302,57.0,0.0,1.183591,130.0,236.0,0.0,0.0,174.0,0.0,0.0,1.0,1.0,2.0